### ISSUE TITLE
Suppress service injection in DbContext ObjectMaterialized event in read only scenarios

### ISSUE THREAD

**Issue by milenkodj** [jprice628/tripping-wookie#1]
It would be good to be able to suppress service injection when not needed, such as in read only scenarios, such as our OData controllers, where entities are just retrieved and mapped out, without a need for service injection.
I was thinking off adding a default DbContext constructor in the LittleLeague, for use in such scenarios. It will not register ObjectMaterialized event handler to start with.

**Comment by jprice628** [comment]
Better than the bool we had before. Done. Get latest, and see if you like it. If you do, close this issue.

**Comment by jprice628** [comment]
Actually...I think I may have come up with a more stable way to do this. Take a look at the latest code. It lazy loads the dependencies only when they are needed. This way is less likely to have null reference exceptions.

**Comment by Insanityisnice** [comment]
I updated the lazy loading to use the lazy class which is a little more standard as well as can handle threading and such if needed.

**Comment by Insanityisnice** [comment]
One thing I don't really like is the event base class.  It assumes to many things.
* All entities have auditing - I've found this is not the case we actually audit way to much on the SSP project its amazing.
* An entity gets log and event raising by default for simple applications that may seem reasonable but giving access to all resources even if lazy loaded forces to much into the entity.

I'd be more in favor of just having each entity spin up the things it needs.

One think this solution doesn't account for is forcing readonly.  I think this can be fixed by using an IDbContext interface and an IReadOnlyDbContext.  The later would not implement save changes so when the ODATA controller injects the later it would not have access to save changes.

**Comment by jprice628** [comment]
heh. Lazy<T> class slipped my mind. Good catch.
